# _*_ mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # GENERAL VAGRANT VM CONFIGURATION
    config.vm.box = "geerlingguy/rockylinux8"
    config.ssh.insert_key = false
    config.vm.synced_folder "." "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
        vb.memory = 256
        vb.linked_clone = true
    end

    config.vm.provision "shell", path: "update_centos_box.sh"
    
    # App Server 1
    config.vm.define "app-1" do |app|
        app.vm.hostname = "orc-app1-test"
        app.vm.network :private_network, ip: "192.168.60.4"
    end

    # App Server 2
    config.vm.define "app-2" do |app|
        app.vm.hostname = "orc-app2-test"
        app.vm.network :private_network, ip: "192.168.60.5"
    end

    # Database Server
    config.vm.define "db" do |db|
        db.vm.hostname = "orc-db.test"
        db.vm.network :private_network, ip: "192.168.60.6"
    end
end
