Vagrant.configure("2") do |config|
  config.vm.box = "williecadete/rhel8-desktop-nocm"
  config.vm.box_version = "0.0.1"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
    vb.memory = "4096"
  end
end