Vagrant.configure("2") do |config|
    config.vm.box = "gusztavvargadr/ubuntu-desktop"
    config.vm.provider "virtualbox" do |vb|
       # Display the VirtualBox GUI when booting the machine
       vb.gui = true
       vb.memory = "4096"
    end
  $script = <<-SHELL
     sudo apt-get update && sudo apt-get upgrade -y
     sudo apt-get install gnupg2 -y
     sudo curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
     sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
     sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
     
     sudo apt-get update -y
     sudo apt-get install -y code
     sudo apt-get install -y git
     
     curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.9/install.sh | bash
     
     export NVM_DIR="$HOME/.nvm"
     [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
     
     nvm install node
     npm install -g gulp
     sudo apt-get install -y --no-install-recommends ubuntu-desktop
     wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
     sudo dpkg -i google-chrome-stable_current_amd64.deb
     sudo apt-get -f -y install
     sudo chown -R vagrant:vagrant /home/vagrant/*
  sudo shutdown -h now
  SHELL
  config.vm.provision "shell", inline: $script, privileged: false
  end